### PR TITLE
Feature/python3

### PR DESCRIPTION
**Pull request by AkhilGNair**
Hi! Thanks for the package.

This PR is to generate Python classes from JSON schema with type hinting + a marshmallow schema class to enable serialisation + deserialisation.

I haven't yet added all the tests, and will likely not add functionality for all json schema features (for now). The PR is a bit premature, sorry about that.

### CODE REVIEW

**Comment by expobrain** [comment]
Hi @AkhilGNair, 

thank you very much for your PR, I'll have a look at it soon!

In the meanwhile can I ask you if you can add some kind of notification like rising a `NotImplementedError` for the feature of JSON-schema which you are not implementing?

**Comment by AkhilGNair** [comment]
Hi - yup I will. Going to slowly add more tests to make sure I catch all the `NotImplemented`s.

Thanks!

**Comment by AkhilGNair** [comment]
Hi @expobrain - The tests for the cases I'm implemented pass. There are a couple of cases that still fail, mainly around arrays of aliases, but they raise a `NotImplementedException`. I'm not sure how to best edit the test case here to show this is expected.

Thanks!

**Comment by expobrain** [comment]
Hi @AkhilGNair, 

thank you for all your amazing work!

I'll have a look today, I'll find a solution for the raised `NotImplementedException` so the unit test will be happy :-)

**Comment by expobrain** [comment]
@AkhilGNair what about something like this:

```
diff --git a/tests/generator_python3_test.py b/tests/generator_python3_test.py
index 5c60de3..9b1fc0f 100644
--- a/tests/generator_python3_test.py
+++ b/tests/generator_python3_test.py
@@ -1,4 +1,5 @@
 import ast
+import warnings

 from pathlib2 import Path
 import pytest
@@ -28,7 +29,12 @@ def test_generate(schema_filename):
     fixture_filename = FIXTURES_DIR / (schema_filename.name.split(".")[0] + ".py")

     schema = load_schema(schema_filename.read_text())
-    fixture = astor.parse_file(str(fixture_filename))
+
+    try:
+        fixture = astor.parse_file(str(fixture_filename))
+    except FileNotFoundError as e:
+        warnings.warn(f"Fixture not implemented yet {fixture_filename}")
+        return

     generator = Python3Generator(schema)
     result = generator.generate().as_ast()
```

so the test will pass but leaving a nice warning about it?

It's a temporary solution until I'll implement the generation for those cases.

**Pull request merged**
